export interface CurrencyInfo {
    code: string
    name: string
    /** Narrow symbol, empty when the only symbol is the code itself. */
    symbol: string
    flag: string
}

// Codes returned by api.exchangerate-api.com/v4 on 2026-09-25. Names and symbols come from
// CLDR (Intl in Node 24); the API may add codes later, those fall back to describeUnknown().
const TABLE: ReadonlyArray<readonly [string, string, string, string]> = [
    ['AED', 'United Arab Emirates Dirham', '', '🇦🇪'],
    ['AFN', 'Afghan Afghani', '؋', '🇦🇫'],
    ['ALL', 'Albanian Lek', '', '🇦🇱'],
    ['AMD', 'Armenian Dram', '֏', '🇦🇲'],
    ['ANG', 'Netherlands Antillean Guilder', '', '🇨🇼'],
    ['AOA', 'Angolan Kwanza', 'Kz', '🇦🇴'],
    ['ARS', 'Argentine Peso', '$', '🇦🇷'],
    ['AUD', 'Australian Dollar', '$', '🇦🇺'],
    ['AWG', 'Aruban Florin', '', '🇦🇼'],
    ['AZN', 'Azerbaijani Manat', '₼', '🇦🇿'],
    ['BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM', '🇧🇦'],
    ['BBD', 'Barbadian Dollar', '$', '🇧🇧'],
    ['BDT', 'Bangladeshi Taka', '৳', '🇧🇩'],
    ['BGN', 'Bulgarian Lev', '', '🇧🇬'],
    ['BHD', 'Bahraini Dinar', '', '🇧🇭'],
    ['BIF', 'Burundian Franc', '', '🇧🇮'],
    ['BMD', 'Bermudan Dollar', '$', '🇧🇲'],
    ['BND', 'Brunei Dollar', '$', '🇧🇳'],
    ['BOB', 'Bolivian Boliviano', 'Bs', '🇧🇴'],
    ['BRL', 'Brazilian Real', 'R$', '🇧🇷'],
    ['BSD', 'Bahamian Dollar', '$', '🇧🇸'],
    ['BTN', 'Bhutanese Ngultrum', '', '🇧🇹'],
    ['BWP', 'Botswanan Pula', 'P', '🇧🇼'],
    ['BYN', 'Belarusian Ruble', '', '🇧🇾'],
    ['BZD', 'Belize Dollar', '$', '🇧🇿'],
    ['CAD', 'Canadian Dollar', '$', '🇨🇦'],
    ['CDF', 'Congolese Franc', '', '🇨🇩'],
    ['CHF', 'Swiss Franc', '', '🇨🇭'],
    ['CLF', 'Chilean Unit of Account (UF)', '', '🇨🇱'],
    ['CLP', 'Chilean Peso', '$', '🇨🇱'],
    ['CNH', 'Chinese Yuan (offshore)', '', '🇨🇳'],
    ['CNY', 'Chinese Yuan', '¥', '🇨🇳'],
    ['COP', 'Colombian Peso', '$', '🇨🇴'],
    ['CRC', 'Costa Rican Colón', '₡', '🇨🇷'],
    ['CUP', 'Cuban Peso', '$', '🇨🇺'],
    ['CVE', 'Cape Verdean Escudo', '', '🇨🇻'],
    ['CZK', 'Czech Koruna', 'Kč', '🇨🇿'],
    ['DJF', 'Djiboutian Franc', '', '🇩🇯'],
    ['DKK', 'Danish Krone', 'kr', '🇩🇰'],
    ['DOP', 'Dominican Peso', '$', '🇩🇴'],
    ['DZD', 'Algerian Dinar', '', '🇩🇿'],
    ['EGP', 'Egyptian Pound', 'E£', '🇪🇬'],
    ['ERN', 'Eritrean Nakfa', '', '🇪🇷'],
    ['ETB', 'Ethiopian Birr', '', '🇪🇹'],
    ['EUR', 'Euro', '€', '🇪🇺'],
    ['FJD', 'Fijian Dollar', '$', '🇫🇯'],
    ['FKP', 'Falkland Islands Pound', '£', '🇫🇰'],
    ['FOK', 'Faroese Króna', '', '🇫🇴'],
    ['GBP', 'British Pound', '£', '🇬🇧'],
    ['GEL', 'Georgian Lari', '₾', '🇬🇪'],
    ['GGP', 'Guernsey Pound', '', '🇬🇬'],
    ['GHS', 'Ghanaian Cedi', 'GH₵', '🇬🇭'],
    ['GIP', 'Gibraltar Pound', '£', '🇬🇮'],
    ['GMD', 'Gambian Dalasi', '', '🇬🇲'],
    ['GNF', 'Guinean Franc', 'FG', '🇬🇳'],
    ['GTQ', 'Guatemalan Quetzal', 'Q', '🇬🇹'],
    ['GYD', 'Guyanaese Dollar', '$', '🇬🇾'],
    ['HKD', 'Hong Kong Dollar', '$', '🇭🇰'],
    ['HNL', 'Honduran Lempira', 'L', '🇭🇳'],
    ['HRK', 'Croatian Kuna', 'kn', '🇭🇷'],
    ['HTG', 'Haitian Gourde', '', '🇭🇹'],
    ['HUF', 'Hungarian Forint', 'Ft', '🇭🇺'],
    ['IDR', 'Indonesian Rupiah', 'Rp', '🇮🇩'],
    ['ILS', 'Israeli New Shekel', '₪', '🇮🇱'],
    ['IMP', 'Manx Pound', '', '🇮🇲'],
    ['INR', 'Indian Rupee', '₹', '🇮🇳'],
    ['IQD', 'Iraqi Dinar', '', '🇮🇶'],
    ['IRR', 'Iranian Rial', '', '🇮🇷'],
    ['ISK', 'Icelandic Króna', 'kr', '🇮🇸'],
    ['JEP', 'Jersey Pound', '', '🇯🇪'],
    ['JMD', 'Jamaican Dollar', '$', '🇯🇲'],
    ['JOD', 'Jordanian Dinar', '', '🇯🇴'],
    ['JPY', 'Japanese Yen', '¥', '🇯🇵'],
    ['KES', 'Kenyan Shilling', '', '🇰🇪'],
    ['KGS', 'Kyrgystani Som', '', '🇰🇬'],
    ['KHR', 'Cambodian Riel', '៛', '🇰🇭'],
    ['KID', 'Kiribati Dollar', '', '🇰🇮'],
    ['KMF', 'Comorian Franc', 'CF', '🇰🇲'],
    ['KRW', 'South Korean Won', '₩', '🇰🇷'],
    ['KWD', 'Kuwaiti Dinar', '', '🇰🇼'],
    ['KYD', 'Cayman Islands Dollar', '$', '🇰🇾'],
    ['KZT', 'Kazakhstani Tenge', '₸', '🇰🇿'],
    ['LAK', 'Laotian Kip', '₭', '🇱🇦'],
    ['LBP', 'Lebanese Pound', 'L£', '🇱🇧'],
    ['LKR', 'Sri Lankan Rupee', 'Rs', '🇱🇰'],
    ['LRD', 'Liberian Dollar', '$', '🇱🇷'],
    ['LSL', 'Lesotho Loti', '', '🇱🇸'],
    ['LYD', 'Libyan Dinar', '', '🇱🇾'],
    ['MAD', 'Moroccan Dirham', '', '🇲🇦'],
    ['MDL', 'Moldovan Leu', '', '🇲🇩'],
    ['MGA', 'Malagasy Ariary', 'Ar', '🇲🇬'],
    ['MKD', 'Macedonian Denar', '', '🇲🇰'],
    ['MMK', 'Myanmar Kyat', 'K', '🇲🇲'],
    ['MNT', 'Mongolian Tugrik', '₮', '🇲🇳'],
    ['MOP', 'Macanese Pataca', '', '🇲🇴'],
    ['MRU', 'Mauritanian Ouguiya', '', '🇲🇷'],
    ['MUR', 'Mauritian Rupee', 'Rs', '🇲🇺'],
    ['MVR', 'Maldivian Rufiyaa', '', '🇲🇻'],
    ['MWK', 'Malawian Kwacha', '', '🇲🇼'],
    ['MXN', 'Mexican Peso', '$', '🇲🇽'],
    ['MYR', 'Malaysian Ringgit', 'RM', '🇲🇾'],
    ['MZN', 'Mozambican Metical', '', '🇲🇿'],
    ['NAD', 'Namibian Dollar', '$', '🇳🇦'],
    ['NGN', 'Nigerian Naira', '₦', '🇳🇬'],
    ['NIO', 'Nicaraguan Córdoba', 'C$', '🇳🇮'],
    ['NOK', 'Norwegian Krone', 'kr', '🇳🇴'],
    ['NPR', 'Nepalese Rupee', 'Rs', '🇳🇵'],
    ['NZD', 'New Zealand Dollar', '$', '🇳🇿'],
    ['OMR', 'Omani Rial', '', '🇴🇲'],
    ['PAB', 'Panamanian Balboa', '', '🇵🇦'],
    ['PEN', 'Peruvian Sol', '', '🇵🇪'],
    ['PGK', 'Papua New Guinean Kina', '', '🇵🇬'],
    ['PHP', 'Philippine Peso', '₱', '🇵🇭'],
    ['PKR', 'Pakistani Rupee', 'Rs', '🇵🇰'],
    ['PLN', 'Polish Zloty', 'zł', '🇵🇱'],
    ['PYG', 'Paraguayan Guarani', '₲', '🇵🇾'],
    ['QAR', 'Qatari Riyal', '', '🇶🇦'],
    ['RON', 'Romanian Leu', 'lei', '🇷🇴'],
    ['RSD', 'Serbian Dinar', '', '🇷🇸'],
    ['RUB', 'Russian Ruble', '₽', '🇷🇺'],
    ['RWF', 'Rwandan Franc', 'RF', '🇷🇼'],
    ['SAR', 'Saudi Riyal', '', '🇸🇦'],
    ['SBD', 'Solomon Islands Dollar', '$', '🇸🇧'],
    ['SCR', 'Seychellois Rupee', '', '🇸🇨'],
    ['SDG', 'Sudanese Pound', '', '🇸🇩'],
    ['SEK', 'Swedish Krona', 'kr', '🇸🇪'],
    ['SGD', 'Singapore Dollar', '$', '🇸🇬'],
    ['SHP', 'St. Helena Pound', '£', '🇸🇭'],
    ['SLE', 'Sierra Leonean Leone', '', '🇸🇱'],
    ['SLL', 'Sierra Leonean Leone (1964—2022)', '', '🇸🇱'],
    ['SOS', 'Somali Shilling', '', '🇸🇴'],
    ['SRD', 'Surinamese Dollar', '$', '🇸🇷'],
    ['SSP', 'South Sudanese Pound', '£', '🇸🇸'],
    ['STN', 'São Tomé & Príncipe Dobra', 'Db', '🇸🇹'],
    ['SYP', 'Syrian Pound', '£', '🇸🇾'],
    ['SZL', 'Swazi Lilangeni', '', '🇸🇿'],
    ['THB', 'Thai Baht', '฿', '🇹🇭'],
    ['TJS', 'Tajikistani Somoni', '', '🇹🇯'],
    ['TMT', 'Turkmenistani Manat', '', '🇹🇲'],
    ['TND', 'Tunisian Dinar', '', '🇹🇳'],
    ['TOP', 'Tongan Paʻanga', 'T$', '🇹🇴'],
    ['TRY', 'Turkish Lira', '₺', '🇹🇷'],
    ['TTD', 'Trinidad & Tobago Dollar', '$', '🇹🇹'],
    ['TVD', 'Tuvaluan Dollar', '', '🇹🇻'],
    ['TWD', 'New Taiwan Dollar', '$', '🇹🇼'],
    ['TZS', 'Tanzanian Shilling', '', '🇹🇿'],
    ['UAH', 'Ukrainian Hryvnia', '₴', '🇺🇦'],
    ['UGX', 'Ugandan Shilling', '', '🇺🇬'],
    ['USD', 'US Dollar', '$', '🇺🇸'],
    ['UYU', 'Uruguayan Peso', '$', '🇺🇾'],
    ['UZS', 'Uzbekistani Som', '', '🇺🇿'],
    ['VES', 'Venezuelan Bolívar', '', '🇻🇪'],
    ['VND', 'Vietnamese Dong', '₫', '🇻🇳'],
    ['VUV', 'Vanuatu Vatu', '', '🇻🇺'],
    ['WST', 'Samoan Tala', '', '🇼🇸'],
    ['XAF', 'Central African CFA Franc', 'FCFA', '🌍'],
    ['XCD', 'East Caribbean Dollar', '$', '🌎'],
    ['XCG', 'Caribbean Guilder', 'Cg.', '🇨🇼'],
    ['XDR', 'Special Drawing Rights', '', '🌐'],
    ['XOF', 'West African CFA Franc', 'F CFA', '🌍'],
    ['XPF', 'CFP Franc', 'CFPF', '🌏'],
    ['YER', 'Yemeni Rial', '', '🇾🇪'],
    ['ZAR', 'South African Rand', 'R', '🇿🇦'],
    ['ZMW', 'Zambian Kwacha', 'ZK', '🇿🇲'],
    ['ZWG', 'Zimbabwean Gold', '', '🇿🇼'],
    ['ZWL', 'Zimbabwean Dollar (2009–2024)', '', '🇿🇼'],
]

export const CURRENCIES: ReadonlyMap<string, CurrencyInfo> = new Map(
    TABLE.map(([code, name, symbol, flag]) => [code, {code, name, symbol, flag}]),
)

export const DEFAULT_SELECTION: readonly string[] = ['USD', 'RUB', 'VND', 'THB', 'KRW']

// Shown first in the add list, before the alphabetical rest.
export const POPULAR: readonly string[] = ['USD', 'EUR', 'GBP', 'JPY', 'CNY', 'CHF', 'CAD', 'AUD', 'HKD', 'SGD', 'INR', 'AED', 'TRY']

export const CURRENCY_CODE = /^[A-Z]{3}$/

function describeUnknown(code: string): CurrencyInfo {
    let name = code
    try {
        name = new Intl.DisplayNames(['en'], {type: 'currency'}).of(code) ?? code
    } catch {
        // Intl.DisplayNames is missing on old engines, the code alone is enough
    }
    return {code, name, symbol: '', flag: '🏳️'}
}

export function currencyInfo(code: string): CurrencyInfo {
    return CURRENCIES.get(code) ?? describeUnknown(code)
}
